server:
  port: 8080

spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:H2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:schema-h2.sql
        - classpath:data-h2.sql
mybatis:
  mapper-locations: classpath:mapper/*.xml